apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      imagePullSecrets:
        - name: dockerconfigjson
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
              name: metrics
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
                optional: false
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/{{ .Release.Name }}/
              name: {{ .Release.Name }}-config
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-config
          secret:
            secretName: {{ .Release.Name }}-config
            optional: false
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
