apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "{{ .Release.Name }}"
type: Opaque
spec:
  itemPath: vaults/{{ .Values.onepassword.vault }}/items/{{ .Values.onepassword.secretName }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "{{ .Release.Name }}-config"
type: Opaque
spec:
  itemPath: vaults/{{ .Values.onepassword.vault }}/items/{{ .Values.onepassword.configSecretName }}