apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - port: 9000
      targetPort: metrics
      protocol: TCP
      name: metrics
  type: ClusterIP
